// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';
import { resolve } from 'path';

// Load .env from the project root (two directories up from lib/auth-db)
config({ path: resolve(__dirname, '../../.env') });

if (!process.env.AUTH_DATABASE_URL) {
  throw new Error('AUTH_DATABASE_URL is not defined in the .env file');
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env.AUTH_DATABASE_URL,
  },
});
